export const ActionTypes = {
  
  GET_LANGUAGES_REQUEST: "GET_LANGUAGES_REQUEST",
  GET_LANGUAGES_SUCCESS: "GET_LANGUAGES_SUCCESS",
  GET_LANGUAGES_FAILURE: "GET_LANGUAGES_FAILURE",

  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",

// PURCHASE_ORDER
PURCHASE_ORDERS_REQUEST: "PURCHASE_ORDERS_REQUEST",
PURCHASE_ORDERS_SUCCESS: "PURCHASE_ORDERS_SUCCESS",
PURCHASE_ORDERS_FAILURE: "PURCHASE_ORDERS_FAILURE",

PURCHASE_ORDER_REQUEST: "PURCHASE_ORDER_REQUEST",
PURCHASE_ORDER_SUCCESS: "PURCHASE_ORDER_SUCCESS",
PURCHASE_ORDER_FAILURE: "PURCHASE_ORDER_FAILURE",

PURCHASE_ORDER_REVIEW_REQUEST: "PURCHASE_ORDER_REVIEW_REQUEST",
PURCHASE_ORDER_REVIEW_SUCCESS: "PURCHASE_ORDER_REVIEW_SUCCESS",
PURCHASE_ORDER_REVIEW_FAILURE: "PURCHASE_ORDER_REVIEW_FAILURE",

UPDATE_PURCHASE_ORDER_REQUEST: "UPDATE_PURCHASE_ORDER_REQUEST",
UPDATE_PURCHASE_ORDER_SUCCESS: "UPDATE_PURCHASE_ORDER_SUCCESS",
UPDATE_PURCHASE_ORDER_FAILURE: "UPDATE_PURCHASE_ORDER_FAILURE",

UPDATE_PURCHASE_ORDER_REVIEW_REQUEST: "UPDATE_PURCHASE_ORDER_REVIEW_REQUEST",
UPDATE_PURCHASE_ORDER_REVIEW_SUCCESS: "UPDATE_PURCHASE_ORDER_REVIEW_SUCCESS",
UPDATE_PURCHASE_ORDER_REVIEW_FAILURE: "UPDATE_PURCHASE_ORDER_REVIEW_FAILURE",

DELETE_PURCHASE_ORDER_REQUEST: "DELETE_PURCHASE_ORDER_REQUEST",
DELETE_PURCHASE_ORDER_SUCCESS: "DELETE_PURCHASE_ORDER_SUCCESS",
DELETE_PURCHASE_ORDER_FAILURE: "DELETE_PURCHASE_ORDER_FAILURE",
};
