export const ActionTypes = {
  //Server notifications
  SET_SERVER_NOTIFICATIONS: "SET_SERVER_NOTIFICATIONS",
  REMOVE_SERVER_NOTIFICATION: "REMOVE_SERVER_NOTIFICATION",

  //Server notifications
  SUCCESS_NOTIFICATIONS: "SUCCESS_NOTIFICATIONS",
  INFO_NOTIFICATIONS: "INFO_NOTIFICATIONS",
  WARNING_NOTIFICATIONS: "WARNING_NOTIFICATIONS",
  ERROR_NOTIFICATIONS: "ERROR_NOTIFICATIONS",

  GET_LANGUAGES_REQUEST: "GET_LANGUAGES_REQUEST",
  GET_LANGUAGES_SUCCESS: "GET_LANGUAGES_SUCCESS",
  GET_LANGUAGES_FAILURE: "GET_LANGUAGES_FAILURE",

  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
  TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",

  // AUTHENTICATE_USER
  AUTHENTICATE_USER_REQUEST: "AUTHENTICATE_USER_REQUEST",
  AUTHENTICATE_USER_SUCCESS: "AUTHENTICATE_USER_SUCCESS",
  AUTHENTICATE_USER_FAILURE: "AUTHENTICATE_USER_FAILURE",

  // REGISTER
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_FAILURE: "REGISTER_FAILURE",

  // VERIFY_IDENTITY
  VERIFY_IDENTITY_REQUEST: "VERIFY_IDENTITY_REQUEST",
  VERIFY_IDENTITY_SUCCESS: "VERIFY_IDENTITY_SUCCESS",
  VERIFY_IDENTITY_FAILURE: "VERIFY_IDENTITY_FAILURE",

  // RESEND_PIN_CODE
  RESEND_PIN_CODE_REQUEST: "RESEND_PIN_CODE_REQUEST",
  RESEND_PIN_CODE_SUCCESS: "RESEND_PIN_CODE_SUCCESS",
  RESEND_PIN_CODE_FAILURE: "RESEND_PIN_CODE_FAILURE",

  // VERIFY_REGISTRATION
  VERIFY_REGISTRATION_REQUEST: "VERIFY_REGISTRATION_REQUEST",
  VERIFY_REGISTRATION_SUCCESS: "VERIFY_REGISTRATION_SUCCESS",
  VERIFY_REGISTRATION_FAILURE: "VERIFY_REGISTRATION_FAILURE",

  // FORGOT_PASSWORD
  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",

  // RESET_PASSWORD
  RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_FAILURE: "RESET_PASSWORD_FAILURE",

  // SIGN_OUT
  SIGN_OUT_REQUEST: "SIGN_OUT_REQUEST",
  SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
  SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",

  // PROFILE_USER
  PROFILE_USER_REQUEST: "PROFILE_USER_REQUEST",
  PROFILE_USER_SUCCESS: "PROFILE_USER_SUCCESS",
  PROFILE_USER_FAILURE: "PROFILE_USER_FAILURE",

  // PROFILES
  PROFILES_REQUEST: "PROFILES_REQUEST",
  PROFILES_SUCCESS: "PROFILES_SUCCESS",
  PROFILES_FAILURE: "PROFILES_FAILURE",

  // DELETE_PROFILE
  DELETE_PROFILE_REQUEST: "DELETE_PROFILE_REQUEST",
  DELETE_PROFILE_SUCCESS: "DELETE_PROFILE_SUCCESS",
  DELETE_PROFILE_FAILURE: "DELETE_PROFILE_FAILURE",

  // UPDATE_EMAIL
  UPDATE_EMAIL_REQUEST: "UPDATE_EMAIL_REQUEST",
  UPDATE_EMAIL_SUCCESS: "UPDATE_EMAIL_SUCCESS",
  UPDATE_EMAIL_FAILURE: "UPDATE_EMAIL_FAILURE",

  // UPDATE_NOTIFICATION
  UPDATE_NOTIFICATION_REQUEST: "UPDATE_NOTIFICATION_REQUEST",
  UPDATE_NOTIFICATION_SUCCESS: "UPDATE_NOTIFICATION_SUCCESS",
  UPDATE_NOTIFICATION_FAILURE: "UPDATE_NOTIFICATION_FAILURE",

  // UPDATE_OTP_EMAIL
  UPDATE_OTP_EMAIL_REQUEST: "UPDATE_OTP_EMAIL_REQUEST",
  UPDATE_OTP_EMAIL_SUCCESS: "UPDATE_OTP_EMAIL_SUCCESS",
  UPDATE_OTP_EMAIL_FAILURE: "UPDATE_OTP_EMAIL_FAILURE",

  // UPDATE_PARAMS
  UPDATE_PARAMS_REQUEST: "UPDATE_PARAMS_REQUEST",
  UPDATE_PARAMS_SUCCESS: "UPDATE_PARAMS_SUCCESS",
  UPDATE_PARAMS_FAILURE: "UPDATE_PARAMS_FAILURE",

  // UPDATE_PHONE
  UPDATE_PHONE_REQUEST: "UPDATE_PHONE_REQUEST",
  UPDATE_PHONE_SUCCESS: "UPDATE_PHONE_SUCCESS",
  UPDATE_PHONE_FAILURE: "UPDATE_PHONE_FAILURE",

  // UPDATE_PICTURE
  UPDATE_PICTURE_REQUEST: "UPDATE_PICTURE_REQUEST",
  UPDATE_PICTURE_SUCCESS: "UPDATE_PICTURE_SUCCESS",
  UPDATE_PICTURE_FAILURE: "UPDATE_PICTURE_FAILURE",

  // UPDATE_PROFILE
  UPDATE_PROFILE_REQUEST: "UPDATE_PROFILE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

  // UPDATE_WEBSITE
  UPDATE_WEBSITE_REQUEST: "UPDATE_WEBSITE_REQUEST",
  UPDATE_WEBSITE_SUCCESS: "UPDATE_WEBSITE_SUCCESS",
  UPDATE_WEBSITE_FAILURE: "UPDATE_WEBSITE_FAILURE",

  // CATEGORY
  CATEGORY_REQUEST: "CATEGORY_REQUEST",
  CATEGORY_SUCCESS: "CATEGORY_SUCCESS",
  CATEGORY_FAILURE: "CATEGORY_FAILURE",

  // CATEGORIES
  CATEGORIES_REQUEST: "CATEGORIES_REQUEST",
  CATEGORIES_SUCCESS: "CATEGORIES_SUCCESS",
  CATEGORIES_FAILURE: "CATEGORIES_FAILURE",

  // DELETE_CATEGORY
  DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_FAILURE: "DELETE_CATEGORY_FAILURE",

  // UPDATE_CATEGORY
  UPDATE_CATEGORY_REQUEST: "UPDATE_CATEGORY_REQUEST",
  UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",

};
