export const GridConstants = {
  HEIGHT: 'calc(100vh - 266px)',
  HEIGHT_TRANSACTION: 'calc(100vh - 400px)',
  HEIGHT_PURCHASE_ORDER: 'calc(100vh - 500px)',
  HEIGHT_DELIVERY: 'calc(100vh - 420px)',
  HEIGHT_Claims: 'calc(100vh - 310px)',
  HEIGHT_BRANCH: 'calc(100vh - 300px)',
  HEIGHT_EXP_MODE: 'calc(100vh - 278px)',
  ETAT: 100,
  DATE_CREATED: 200,

  HEIGHT_VEHICLE: 'calc(100vh - 300px)',
  HEIGHT_SCHEDULE: 'calc(100vh - 174px)',
  HEIGHT_PURCHASE: 'calc(27vh)',
  HEIGHT_PURCHASE_ORDER_DETAILS: 'calc(16vh)',
  ROWS_PER_PAGE: 25,
};

export const SidebarAgenciesFormData = {
  NAME: 'name',
  TOWN: 'town',
  CURRENCY_POSITION: 'currencyPosition',
  IS_HEAD_QUARTER: 'isHeadQuarter',
  LANGUAGE: 'language',
  REGIONAL_FORMAT: 'regionalFormat',
  TIMEZONE: 'timeZone',
  DESCRIPTION: 'description',
  LONGITUDE: 'longitude',
  LATITUDE: 'latitude',
  RADIUS: 'radius',
}

export const SidebarProvidersFormData = {
  NAME: 'name',
  TOWN: 'town',
  ADDRESS: 'address',
  REFERENCE: 'reference',
  NIU: 'niu',
  EMAIL1: 'email1',
  EMAIL2: 'email2',
  PHONE_NUMBER1: 'phoneNumber1',
  PHONE_NUMBER2: 'phoneNumber2',
  DESCRIPTION: 'description',
  IBAN: 'iban',
  BANK: 'bankId',
  LASTNAME: 'lastName',
  FIRSTNAME: 'firstName',
  MIDDLENAME: 'middleName',
  IS_REVOKED: 'isRevoked',
  REVOKED_ON: 'revokedOn',
  REVOKED_BY: 'revokedBy',
  REVOCATION_REASON: 'revocationResaon',
}

export const SidebarClaimFormData = {
  AGENCY: 'agency',
  TRACKING_NUMBER_CLAIM: 'trackingNumberClaim',
  STATUS: 'status',
  DEPART: 'depart',
  ARRIVE: 'arrive',
  TRACKING_NUMBER: 'trackingNumber',
  FULLNAME: 'fullName',
  EMAIL: 'email',
  PHONENUMBER: 'phoneNumber',
  RECLAMATION: 'reclamation',
  COMPLAINT_TYPE: 'complaintType',
  OTHER_COMPLAINT_TYPE: 'otherComplaintType',
  RECEIVE_PHONE_CALLS: 'receivePhoneCalls',
}

export const SidebarBrandFormData = {
  TITLE: 'title',
  DESCRIPTION: 'description',
  TITLE_MODEL: 'title',
  DESCRIPTION_MODEL: 'description',

}
export const SidebarResetPasswordUserFormData = {
  IS_PASSWORD_AUTO_GENERATED: 'isPasswordAutoGenerated',
  PASSWORD: 'password',
  PASSWORD_CONFIRM: 'passwordConfirmation',
  DESTINATION_EMAIL: 'destinationEmailAddress',

}
export const SidebarUesrsormData = {
  USERNAME: 'userName',
  IS_PASSWORD_AUTO_GENERATED: 'isPasswordAutoGenerated',
  PASSWORD: 'password',
  CONFIRM_PASSWORD: 'confirmPassword',
  FIRSTNAME: 'firstName',
  LASTNAME: 'lastName',
  MIDDLENAME: 'middleName',
  IDENTITY_DOCUMENT_TYPE: 'identityDocumentType',
  IDCARD_NUMBER: 'idCardNumber',
  BRANCHE: 'branche',
  DEPARTMENT: 'department',
  IS_TWO_FACTOR_ENABLED: 'isTwoFactorEnabled',
  EMAIL: 'email',
  EMAIL_CONFIRMATION: 'emailConfirmation',
  PHONE_NUMBER: 'phoneNumber',
  CHOSEN_NOTIFICATION_CHANNEL: 'choosenNotificationChannel',
  IS_USER_CONSENT_SMS_NOTIFICATION: 'isUserConsentSmsNotification',
  IS_USER_CONSENT_EMAIL_NOTIFICATION: 'isUserConsentEmailNotification',
  ROLES: 'roles',
}


export const SidebarDriverFormData = {
  USERID: 'UserId',
  CODE: 'Code',
  DESCRIPTION: 'Description',
  DOCUMENT: 'Document',
}
export const SidebarRouteFormData = {
  TOWN_FORM: 'townForm',
  CODE: 'code',
  TOWN_TO: 'townTo',
  ROUTE_DESCRIPTION: 'routeDescription',
  NAME: 'name',
  LOITERING_DELAY: 'loiteringDelay',
  EXPIRATION_DURATION: 'expirationDuration',
  LONGITUDE: 'longitude',
  LATITUDE: 'latitude',
  RADIUS: 'radius',
  ORDER: 'order',
  TOWN: 'town',
  DESCRIPTION: 'description',
}

export const SupplierOffersFormData = {
  ID: "Id",
  SUPPLIER_ID: "SupplierId",
  REFERENCE: "Reference",
  PURCHASE_REQUEST_ID: "PurchaseRequestId",
  IS_DRAFT: "IsDraft",
  VAT_ID: "VATId",
  IS_VAT_APPLICABLE: "IsVATApplicable",
  CAN_APPLY_VAT: "CanApplyVAT",
  DESCRIPTION: "Description",
  DELIVERY_TIME: "DeliveryTime",
  TIME_DIVISION: "TimeDivision",
  SUBMISSION_DATE: "SubmissionDate",
  ATTACHED: "Attached",
  ITEMS: "Items"
}